#!/bin/sh
# ── Portal — one-shot installer (prebuilt image) ──────────────────────────────
#
# Runs the portal on any machine that has Docker, with no source code, no git,
# no Python, and no compiler on the host. Everything is driven from the
# prebuilt image on the GitHub Container Registry.
#
# What it does:
#   1. Checks Docker + Docker Compose are available
#   2. Asks for club name, short code and a host port
#   3. Generates the three secret keys for you (inside a throwaway container)
#   4. Writes a .env file
#   5. Pulls the image
#   6. Creates your first admin user (interactive)
#   7. Starts the portal and prints the local address
#
# Usage (from the folder containing docker-compose.deploy.yml):
#   sh install.sh
#
# Re-running is safe: if a .env already exists you'll be asked before it's
# touched, and the admin step can be skipped.

set -eu

COMPOSE_FILE="docker-compose.deploy.yml"
ENV_FILE=".env"
SECRET_IMAGE="python:3.11-slim"

# ── 0. Helpers ────────────────────────────────────────────────────────────────
say()  { printf '%s\n' "$*"; }
ask()  { # ask "Prompt" "default" -> echoes answer
  _p="$1"; _d="${2:-}"
  if [ -n "$_d" ]; then printf '%s [%s]: ' "$_p" "$_d" >&2; else printf '%s: ' "$_p" >&2; fi
  read -r _a || true
  [ -z "$_a" ] && _a="$_d"
  printf '%s' "$_a"
}

# Pick the right compose invocation: prefer "docker compose", fall back to
# the legacy "docker-compose" binary.
compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose -f "$COMPOSE_FILE" "$@"
  else
    docker-compose -f "$COMPOSE_FILE" "$@"
  fi
}

say "=================================================="
say "  Portal installer"
say "=================================================="
say ""

# ── 1. Pre-flight checks ──────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  say "ERROR: Docker is not installed or not on PATH."
  say "On a QNAP NAS install 'Container Station' from the App Center first."
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  say "ERROR: Docker is installed but the daemon is not reachable."
  say "Start Docker / Container Station and run this again."
  exit 1
fi

if [ ! -f "$COMPOSE_FILE" ]; then
  say "ERROR: $COMPOSE_FILE not found in this folder."
  say "Place install.sh next to $COMPOSE_FILE and run it from there."
  exit 1
fi

# ── 2. Gather details ─────────────────────────────────────────────────────────
say "Tell me about this instance. Press Enter to accept the [default]."
say ""
CLUB_NAME=$(ask "Club full name (e.g. Demo Youth Club)" "Demo Youth Club")
CLUB_SHORT=$(ask "Short code for member IDs (e.g. DYC)" "DEMO")
CLUB_SHORT=$(printf '%s' "$CLUB_SHORT" | tr '[:lower:]' '[:upper:]')
PORT=$(ask "Host port to serve on" "5001")
IMAGE_TAG=$(ask "Image to run" "ghcr.io/nikster2703/ayc-portal:latest")

# ── 3. Guard an existing .env ─────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
  say ""
  say "A $ENV_FILE already exists in this folder."
  OVERWRITE=$(ask "Overwrite it? Existing secret keys will be LOST (yes/no)" "no")
  case "$OVERWRITE" in
    y|Y|yes|YES) say "Overwriting $ENV_FILE …" ;;
    *) say "Keeping existing $ENV_FILE. Skipping secret generation."; SKIP_ENV=1 ;;
  esac
fi

# ── 4. Generate secrets + write .env ──────────────────────────────────────────
if [ -z "${SKIP_ENV:-}" ]; then
  say ""
  say "Generating secret keys (pulling a small helper image the first time)…"

  # One container prints all three keys, newline-separated, in a fixed order.
  KEYS=$(docker run --rm "$SECRET_IMAGE" sh -c \
    "pip install -q cryptography >/dev/null 2>&1; python3 -c \"import secrets;from cryptography.fernet import Fernet;print(secrets.token_hex(32));print(secrets.token_urlsafe(32));print(Fernet.generate_key().decode())\"")

  SECRET_KEY=$(printf '%s\n' "$KEYS" | sed -n '1p')
  DB_KEY=$(printf '%s\n' "$KEYS" | sed -n '2p')
  DOC_KEY=$(printf '%s\n' "$KEYS" | sed -n '3p')

  if [ -z "$SECRET_KEY" ] || [ -z "$DB_KEY" ] || [ -z "$DOC_KEY" ]; then
    say "ERROR: secret generation failed. Aborting before writing $ENV_FILE."
    exit 1
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date)
# ── KEEP THIS FILE SAFE — back up DB_ENCRYPTION_KEY and DOCUMENT_ENCRYPTION_KEY.
#    If you lose them, the database and uploaded documents are unrecoverable. ──

PORT=$PORT

CLUB_NAME=$CLUB_NAME
CLUB_SHORT_NAME=$CLUB_SHORT

SECRET_KEY=$SECRET_KEY
FLASK_ENV=production

DB_ENCRYPTION_KEY=$DB_KEY
DOCUMENT_ENCRYPTION_KEY=$DOC_KEY

# ── Optional: address lookup on the registration form ─────────────────────────
GETADDRESS_KEY=

# ── Optional: Gmail SMTP for mailshots (add later) ────────────────────────────
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM=
EOF

  say "Wrote $ENV_FILE."
fi

# Make the chosen image available to compose for this run.
export PORTAL_IMAGE="$IMAGE_TAG"

# ── 5. Pull the image ─────────────────────────────────────────────────────────
say ""
say "Pulling $IMAGE_TAG …"
compose pull

# ── 6. First admin user ───────────────────────────────────────────────────────
say ""
MAKE_ADMIN=$(ask "Create the first admin user now? (yes/no)" "yes")
case "$MAKE_ADMIN" in
  y|Y|yes|YES)
    say "Follow the prompts to set the admin username and password…"
    compose run --rm portal python scripts/seed_admin.py
    ;;
  *) say "Skipping admin creation. Run later with:";
     say "  docker compose -f $COMPOSE_FILE run --rm portal python scripts/seed_admin.py" ;;
esac

# ── 7. Start ──────────────────────────────────────────────────────────────────
say ""
say "Starting the portal…"
compose up -d

# Best-effort local IP detection for the closing message.
HOST_IP=$(hostname -i 2>/dev/null | awk '{print $1}')
[ -z "${HOST_IP:-}" ] && HOST_IP="<this-machine-ip>"

say ""
say "=================================================="
say "  Done. The portal is running."
say ""
say "  On this machine:   http://localhost:$PORT"
say "  On the network:    http://$HOST_IP:$PORT"
say ""
say "  No DuckDNS or HTTPS is needed for local use."
say "  Public HTTPS (DuckDNS + Caddy) can be added later."
say "=================================================="
