"""
new_club.py — Provision a new club instance for the AYC Portal.

Run from inside the ayc-portal directory:
    python3 scripts/new_club.py

What this script does:
  1. Asks for club details (name, abbreviation, subdomain, port)
  2. Creates  instances/<slug>/  with a data/ subdirectory
  3. Generates a .env with a fresh SECRET_KEY and DB_ENCRYPTION_KEY
  4. Initialises the encrypted database from schema.sql
  5. Optionally creates the first admin user
  6. Writes a launchd plist (macOS) or systemd unit (Linux)
  7. Writes an nginx server-block snippet
  8. Prints next steps

Requirements:
    pip install sqlcipher3 bcrypt python-dotenv   (already in requirements.txt)
"""

import getpass
import os
import platform
import re
import secrets
import sys

import sqlcipher3
from dotenv import load_dotenv

# ── Paths ──────────────────────────────────────────────────────────────────────

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
BASE_DIR    = os.path.dirname(SCRIPT_DIR)
SCHEMA_PATH = os.path.join(BASE_DIR, 'schema.sql')
INST_ROOT   = os.path.join(BASE_DIR, 'instances')


# ── Helpers ────────────────────────────────────────────────────────────────────

def slugify(text):
    """Convert club name to a safe directory/service name, e.g. 'Bedford FC' → 'bedfordfc'."""
    return re.sub(r'[^a-z0-9]', '', text.lower())


def validate_password(password):
    if len(password) < 8:
        return 'Password must be at least 8 characters'
    if not re.search(r'[A-Z]', password):
        return 'Password must contain at least one uppercase letter'
    if not re.search(r'[0-9]', password):
        return 'Password must contain at least one number'
    if not re.search(r'[^A-Za-z0-9]', password):
        return 'Password must contain at least one special character'
    return None


def connect_db(db_path, key):
    """Open a SQLCipher-encrypted connection and verify the key immediately."""
    conn = sqlcipher3.connect(db_path)
    conn.execute(f"PRAGMA key='{key}'")
    conn.execute('SELECT count(*) FROM sqlite_master')  # raises if key is wrong
    return conn


# ── Steps ──────────────────────────────────────────────────────────────────────

def gather_details():
    print('\n=== AYC Portal — Provision New Club Instance ===\n')

    club_name = input('Club full name  (e.g. Bedford Youth Club): ').strip()
    if not club_name:
        sys.exit('Club name cannot be empty.')

    club_short = input('Club abbreviation  (e.g. BYC — used for member IDs and page titles): ').strip().upper()
    if not club_short:
        sys.exit('Club abbreviation cannot be empty.')

    slug = slugify(club_name)
    suggested_slug = slug
    print(f'Instance slug  (directory + service name): {suggested_slug}')
    override = input('Press Enter to accept, or type a different slug: ').strip()
    if override:
        slug = re.sub(r'[^a-z0-9\-]', '', override.lower())
        if not slug:
            sys.exit('Slug cannot be empty.')

    subdomain = input(f'Subdomain  (e.g. {slug}.yourportal.com): ').strip()
    if not subdomain:
        sys.exit('Subdomain cannot be empty.')

    while True:
        port_str = input('Port number  (e.g. 5002 — must be unique per instance): ').strip()
        if port_str.isdigit() and 1024 <= int(port_str) <= 65535:
            port = int(port_str)
            break
        print('Please enter a valid port number between 1024 and 65535.')

    smtp_from = input(f'MAIL_FROM  (e.g. {club_name} <club@gmail.com>): ').strip()
    if not smtp_from:
        smtp_from = f'{club_name} <yourclub@gmail.com>'

    return {
        'club_name':   club_name,
        'club_short':  club_short,
        'slug':        slug,
        'subdomain':   subdomain,
        'port':        port,
        'smtp_from':   smtp_from,
    }


def create_directories(slug):
    inst_dir  = os.path.join(INST_ROOT, slug)
    data_dir  = os.path.join(inst_dir, 'data')
    doc_dir   = os.path.join(data_dir, 'documents')
    for d in (inst_dir, data_dir, doc_dir):
        os.makedirs(d, exist_ok=True)
    print(f'✓  Created {inst_dir}')
    return inst_dir


def write_env(inst_dir, details, secret_key, db_key):
    env_path = os.path.join(inst_dir, '.env')
    content = f"""# Generated by new_club.py — keep this file SECRET, never commit it.

# Flask
SECRET_KEY={secret_key}
FLASK_ENV=production

# Club identity
CLUB_NAME={details['club_name']}
CLUB_SHORT_NAME={details['club_short']}

# Gmail SMTP — fill in real credentials
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=yourclub@gmail.com
MAIL_PASSWORD=xxxx xxxx xxxx xxxx
MAIL_FROM={details['smtp_from']}

# Postcode lookup (Ideal Postcodes) — optional
GETADDRESS_KEY=

# Database encryption — KEEP THIS SAFE, losing it = permanent data loss
DB_ENCRYPTION_KEY={db_key}
"""
    with open(env_path, 'w') as f:
        f.write(content)
    os.chmod(env_path, 0o600)
    print(f'✓  Generated .env  (permissions 600)')
    return env_path


def init_database(inst_dir, db_key):
    db_path = os.path.join(inst_dir, 'data', 'ayc.db')
    conn = connect_db(db_path, db_key)
    with open(SCHEMA_PATH, 'r') as f:
        conn.executescript(f.read())
    conn.commit()
    conn.close()
    print(f'✓  Database initialised at {db_path}')
    return db_path


def create_admin(db_path, db_key):
    try:
        import bcrypt
    except ImportError:
        print('  ⚠  bcrypt not installed — skipping admin user creation.')
        print('     Run:  pip install bcrypt  then run:  python3 scripts/seed_admin.py')
        return

    print('\n── Create first admin user ──')
    username = input('Username: ').strip()
    if not username:
        print('  Skipping admin user (username was empty).')
        return

    email = input('Email (optional): ').strip()

    while True:
        password = getpass.getpass('Password (min 8 chars, 1 uppercase, 1 number, 1 special): ')
        error = validate_password(password)
        if error:
            print(f'  {error}. Try again.')
            continue
        confirm = getpass.getpass('Confirm password: ')
        if password != confirm:
            print('  Passwords do not match. Try again.')
            continue
        break

    pw_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    conn = connect_db(db_path, db_key)
    try:
        conn.execute(
            'INSERT INTO users (username, email, password_hash, role) VALUES (?,?,?,?)',
            (username, email, pw_hash, 'admin')
        )
        conn.commit()
        print(f"✓  Admin user '{username}' created.")
    except Exception as e:
        print(f'  ⚠  Could not create user: {e}')
    finally:
        conn.close()


def write_service_file(inst_dir, slug, details, app_py_path):
    """Write a launchd plist (macOS) or systemd unit (Linux)."""
    system = platform.system()

    if system == 'Darwin':
        # ── launchd plist ──────────────────────────────────────────────────────
        venv_python = os.path.join(BASE_DIR, 'venv', 'bin', 'python3')
        label       = f'com.ayc-portal.{slug}'
        log_dir     = os.path.join(inst_dir, 'logs')
        os.makedirs(log_dir, exist_ok=True)
        plist_path  = os.path.join(inst_dir, f'{label}.plist')

        plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>

    <key>ProgramArguments</key>
    <array>
        <string>{venv_python}</string>
        <string>{app_py_path}</string>
    </array>

    <key>EnvironmentVariables</key>
    <dict>
        <key>INSTANCE_DIR</key>
        <string>{inst_dir}</string>
        <key>PORT</key>
        <string>{details['port']}</string>
    </dict>

    <key>WorkingDirectory</key>
    <string>{BASE_DIR}</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>StandardOutPath</key>
    <string>{log_dir}/stdout.log</string>

    <key>StandardErrorPath</key>
    <string>{log_dir}/stderr.log</string>
</dict>
</plist>
"""
        with open(plist_path, 'w') as f:
            f.write(plist)
        print(f'✓  launchd plist written: {plist_path}')

        install_path = os.path.expanduser(f'~/Library/LaunchAgents/{label}.plist')
        print(f'\n── macOS next steps ──')
        print(f'  1. Copy the plist to LaunchAgents:')
        print(f'       cp "{plist_path}" "{install_path}"')
        print(f'  2. Load it:')
        print(f'       launchctl load "{install_path}"')
        print(f'  3. Check it started:')
        print(f'       launchctl list | grep {slug}')

    else:
        # ── systemd unit ───────────────────────────────────────────────────────
        venv_gunicorn = os.path.join(BASE_DIR, 'venv', 'bin', 'gunicorn')
        unit_name     = f'ayc-portal-{slug}'
        unit_path     = os.path.join(inst_dir, f'{unit_name}.service')

        unit = f"""[Unit]
Description=AYC Portal — {details['club_name']}
After=network.target

[Service]
Type=simple
WorkingDirectory={BASE_DIR}
Environment=INSTANCE_DIR={inst_dir}
Environment=PORT={details['port']}
ExecStart={venv_gunicorn} --workers 2 --bind 127.0.0.1:{details['port']} app:app
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""
        with open(unit_path, 'w') as f:
            f.write(unit)
        print(f'✓  systemd unit written: {unit_path}')

        print(f'\n── Linux next steps ──')
        print(f'  1. Copy the unit file:')
        print(f'       sudo cp "{unit_path}" /etc/systemd/system/{unit_name}.service')
        print(f'  2. Reload and enable:')
        print(f'       sudo systemctl daemon-reload')
        print(f'       sudo systemctl enable --now {unit_name}')
        print(f'  3. Check status:')
        print(f'       sudo systemctl status {unit_name}')


def write_nginx_config(inst_dir, slug, details):
    nginx_path = os.path.join(inst_dir, f'nginx-{slug}.conf')
    config = f"""# nginx server block for {details['club_name']}
# Place this in /etc/nginx/sites-available/{slug} and symlink to sites-enabled/
# Then: sudo nginx -t && sudo systemctl reload nginx

server {{
    listen 80;
    server_name {details['subdomain']};

    # Redirect HTTP → HTTPS (uncomment after setting up SSL)
    # return 301 https://$host$request_uri;

    location / {{
        proxy_pass         http://127.0.0.1:{details['port']};
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }}
}}

# HTTPS block — run certbot first:
#   sudo certbot --nginx -d {details['subdomain']}
# Then certbot will add the SSL config automatically.
"""
    with open(nginx_path, 'w') as f:
        f.write(config)
    print(f'✓  nginx config written: {nginx_path}')
    return nginx_path


def print_summary(details, inst_dir, env_path):
    print(f"""
══════════════════════════════════════════════════════════
  Instance ready: {details['club_name']}
══════════════════════════════════════════════════════════

  Instance directory : {inst_dir}
  .env               : {env_path}
  Port               : {details['port']}
  Subdomain          : {details['subdomain']}

  ⚠  Before going live:
     • Open {env_path} and fill in MAIL_USERNAME,
       MAIL_PASSWORD, and GETADDRESS_KEY.
     • Back up DB_ENCRYPTION_KEY somewhere secure
       (iCloud Passwords / locked note). Losing it =
       permanent data loss.
     • Set up nginx + SSL (certbot) using the
       generated nginx config file.

══════════════════════════════════════════════════════════
""")


# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    # Confirm schema exists before doing anything
    if not os.path.exists(SCHEMA_PATH):
        sys.exit(f'ERROR: schema.sql not found at {SCHEMA_PATH}\n'
                 'Run this script from inside the ayc-portal directory.')

    details    = gather_details()
    slug       = details['slug']
    inst_dir   = create_directories(slug)

    secret_key = secrets.token_hex(32)
    db_key     = secrets.token_urlsafe(32)

    env_path   = write_env(inst_dir, details, secret_key, db_key)
    db_path    = init_database(inst_dir, db_key)

    want_admin = input('\nCreate admin user now? [Y/n]: ').strip().lower()
    if want_admin != 'n':
        create_admin(db_path, db_key)

    app_py_path = os.path.join(BASE_DIR, 'app.py')
    write_service_file(inst_dir, slug, details, app_py_path)
    write_nginx_config(inst_dir, slug, details)
    print_summary(details, inst_dir, env_path)


if __name__ == '__main__':
    main()
